### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by matsushitas** [sakoken/sshh#3]
```
$ brew install sakoken/sshh/sshh
```

```
$ sshh                                                                                               [~]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11fffa5]

goroutine 1 [running]:
github.com/sakoken/sshh/connector.(*ConnectorCollection).ResetPosition(0x0, 0x22)
	/Users/sakotakenji/project/sshh/connector/connectors.go:34 +0x5
github.com/sakoken/sshh/config.SshhData.func1()
	/Users/sakotakenji/project/sshh/config/sshh.go:15 +0x59
sync.(*Once).Do(0x1567b50, 0x130a600)
	/Users/sakotakenji/.anyenv/envs/goenv/versions/1.12.1/src/sync/once.go:44 +0xb3
github.com/sakoken/sshh/config.SshhData(0xc0000d0420)
	/Users/sakotakenji/project/sshh/config/sshh.go:13 +0x39
main.initSshh()
	/Users/sakotakenji/project/sshh/main.go:62 +0x11b
main.before.func1(0xc0000b47e0, 0xc0000b4700, 0x0)
	/Users/sakotakenji/project/sshh/main.go:47 +0x20
gopkg.in/urfave/cli%2ev2.(*App).Run(0xc000078480, 0xc0000a8000, 0x1, 0x1, 0x0, 0x0)
	/Users/sakotakenji/go/1.12.1/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/app.go:247 +0x6ac
main.main()
	/Users/sakotakenji/project/sshh/main.go:40 +0x22d
```

OS: macOS Mojave

**Comment by sakoken** [comment]
https://github.com/sakoken/sshh/commit/a8e2114405c38abab03135381c23b1d2350a957b
